# 라이브러리 설치

In [1]:
# pip install -r req 쓰지만 추가로 설치하고 싶을 때

!pip install numpy

In [6]:
# 라이브러리에서 책을 꺼내는 것과 같음 
import numpy as np
print(np.__version__)

#설명서 읽고 싶을 땐 help() 사용하기

2.1.1


In [7]:
num1 = [1, 2, 3]
num2 = [4, 5, 6]

#      [5, 7, 9]

[1, 2, 3, 4, 5, 6]

In [8]:
num1_arr = np.array(num1)
num2_arr = np.array(num2)

num1_arr + num2_arr

array([5, 7, 9])

In [10]:
print(type(num1_arr))
# 속성, 메서드

<class 'numpy.ndarray'>


In [22]:
# 전치 배열
num1_arr.T

array([1, 2, 3])

In [17]:
# 해당 열의 데이터 타입
num1_arr.data

In [24]:
# 배열 요소의 데이터 유형
num1_arr.dtype

dtype('int64')

In [25]:
# 정수 튜플
num1_arr.shape

(3,)

In [26]:
# 정수 튜플
num1_arr.ndim

1

In [27]:
# 최댓값
num1_arr.max()

np.int64(3)

In [29]:
num1_arr = np.array(num1, dtype="int8")
num1_arr.dtype

dtype('int8')

## 배열 만드는 방법

In [41]:
# 기본적으로 다른 데이터 자료형으로 numpy 배열로 변환
# 배열 생성
print(np.ones(3))
print(np.zeros(5))

[1. 1. 1.]
[0. 0. 0. 0. 0.]


In [53]:
# 1차원, 2차원, 3차원..
print(np.ndarray(shape=(2,2), dtype=float, order='F'))

[[0. 0.]
 [0. 0.]]


In [52]:
array = np.ndarray(shape=(3,3), dtype=float, order='F')

print(array)
array.shape

[[ 1.27189941e-30 -2.54379882e-30  6.35949704e-31]
 [-2.54379882e-30  5.53276243e-30 -1.71706420e-30]
 [ 6.35949704e-31 -1.71706420e-30  9.85722042e-31]]


(3, 3)

In [54]:
temp_arr = np.arange(16)
temp_arr.reshape(1, 2, 8)

array([[[ 0,  1,  2,  3,  4,  5,  6,  7],
        [ 8,  9, 10, 11, 12, 13, 14, 15]]])

In [57]:
temp_arr = np.arange(16)
# temp_arr.reshape(2, 2, 8) -> 16 사이즈와 맞지 않아서 오류남

In [61]:
# 비트의 중요성
a16 = np.array([1.333333], dtype = np.float16)
a32 = np.array([1.333333], dtype = np.float32)
a64 = np.array([1.333333], dtype = np.float64)
print(a16/3)
print(a32/3)
print(a64/3)

[0.4443]
[0.44444433]
[0.44444433]


In [65]:
arr = np.array([-1, 2, -3])
arr/0 
# 0으로 나눌 때 오류남 

/var/folders/4t/lxzd9js10cb1w262tdv6bk740000gn/T/ipykernel_34590/285127068.py:2: RuntimeWarning: divide by zero encountered in divide
  arr/0


array([-inf,  inf, -inf])

결측치
- Missing Values : 잃어버린 값
- nan : Not a Number -> 아직 정의되지 않은 숫자

In [67]:
print(np.nan, type(np.nan))
print(np.nan, type(np.inf))
print(-np.nan, type(-np.nan))

nan <class 'float'>
nan <class 'float'>
nan <class 'float'>


In [69]:
# 에러가 아니지만, 결측값이 존재하므로 나타나는 값 (결측값 혹은 무한대값)
arr = np.array([-1, 2, -3])
print(arr + np.nan)
print(arr + np.inf)

[nan nan nan]
[inf inf inf]


# 인덱싱 & 슬라이싱

In [70]:
arr = np.arange(10)
arr[1:5]

array([1, 2, 3, 4])

In [77]:
# arr = np.arange(10).reshape(2,5)
arr = np.arange(10).reshape(2,5)
arr[0][1]

np.int64(1)

In [82]:
arr = np.arange(10000).reshape(100,100)
# arr[0:4][0:1]

In [86]:
arr = np.arange(4).reshape(2,2)
arr[:2]

array([[0, 1],
       [2, 3]])

In [112]:
arr = np.arange(20).reshape(4, 5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [113]:
# [행슬라이싱, 열슬라이싱] 
# arr[1:4, 2:5] or arr[1:, 2:]

arr[1:4, 2:5]

array([[ 7,  8,  9],
       [12, 13, 14],
       [17, 18, 19]])

In [111]:
arr[1:, 2:]

array([[ 7,  8,  9],
       [12, 13, 14],
       [17, 18, 19]])

In [115]:
# arr[행, 열]
arr[1:, 3:]

array([[ 8,  9],
       [13, 14],
       [18, 19]])

# 브로드캐스팅 연산
- 받은 행렬의 크기가 다른 경우가 많음
- 크기가 다른 배열 간의 연산도 자동으로 맞춰서 처리하는 연산법

In [116]:
a = np.array([1, 2, 3])
b = np.array([1, 2, 3])
a + b

array([2, 4, 6])

In [119]:
a = np.array([1, 2, 3])
b = 3.0  # [3.0, 3.0, 3.0] 형태의 1차원 배열 생성
a + b

array([4., 5., 6.])

In [120]:
A = np.array([[1, 2], [3, 4]])
B = np.array([10, 20])

print(A + B)  # B가 A의 각 행에 더해짐 (브로드캐스팅)

[[11 22]
 [13 24]]
