# 라이브러리 설치

In [1]:
# pip install -r req 쓰지만 추가로 설치하고 싶을 때

!pip install numpy

In [6]:
# 라이브러리에서 책을 꺼내는 것과 같음 
import numpy as np
print(np.__version__)

#설명서 읽고 싶을 땐 help() 사용하기

2.1.1


In [7]:
num1 = [1, 2, 3]
num2 = [4, 5, 6]

#      [5, 7, 9]

[1, 2, 3, 4, 5, 6]

In [8]:
num1_arr = np.array(num1)
num2_arr = np.array(num2)

num1_arr + num2_arr

array([5, 7, 9])

In [10]:
print(type(num1_arr))
# 속성, 메서드

<class 'numpy.ndarray'>


In [22]:
# 전치 배열
num1_arr.T

array([1, 2, 3])

In [17]:
# 해당 열의 데이터 타입
num1_arr.data

In [24]:
# 배열 요소의 데이터 유형
num1_arr.dtype

dtype('int64')

In [25]:
# 정수 튜플
num1_arr.shape

(3,)

In [26]:
# 정수 튜플
num1_arr.ndim

1

In [27]:
# 최댓값
num1_arr.max()

np.int64(3)

In [29]:
num1_arr = np.array(num1, dtype="int8")
num1_arr.dtype

dtype('int8')

## 배열 만드는 방법

In [41]:
# 기본적으로 다른 데이터 자료형으로 numpy 배열로 변환
# 배열 생성
print(np.ones(3))
print(np.zeros(5))

[1. 1. 1.]
[0. 0. 0. 0. 0.]


In [53]:
# 1차원, 2차원, 3차원..
print(np.ndarray(shape=(2,2), dtype=float, order='F'))

[[0. 0.]
 [0. 0.]]


In [52]:
array = np.ndarray(shape=(3,3), dtype=float, order='F')

print(array)
array.shape

[[ 1.27189941e-30 -2.54379882e-30  6.35949704e-31]
 [-2.54379882e-30  5.53276243e-30 -1.71706420e-30]
 [ 6.35949704e-31 -1.71706420e-30  9.85722042e-31]]


(3, 3)

In [54]:
temp_arr = np.arange(16)
temp_arr.reshape(1, 2, 8)

array([[[ 0,  1,  2,  3,  4,  5,  6,  7],
        [ 8,  9, 10, 11, 12, 13, 14, 15]]])

In [57]:
temp_arr = np.arange(16)
# temp_arr.reshape(2, 2, 8) -> 16 사이즈와 맞지 않아서 오류남

In [61]:
# 비트의 중요성
a16 = np.array([1.333333], dtype = np.float16)
a32 = np.array([1.333333], dtype = np.float32)
a64 = np.array([1.333333], dtype = np.float64)
print(a16/3)
print(a32/3)
print(a64/3)

[0.4443]
[0.44444433]
[0.44444433]


In [65]:
arr = np.array([-1, 2, -3])
arr/0 
# 0으로 나눌 때 오류남 

/var/folders/4t/lxzd9js10cb1w262tdv6bk740000gn/T/ipykernel_34590/285127068.py:2: RuntimeWarning: divide by zero encountered in divide
  arr/0


array([-inf,  inf, -inf])

결측치
- Missing Values : 잃어버린 값
- nan : Not a Number -> 아직 정의되지 않은 숫자

In [67]:
print(np.nan, type(np.nan))
print(np.nan, type(np.inf))
print(-np.nan, type(-np.nan))

nan <class 'float'>
nan <class 'float'>
nan <class 'float'>


In [69]:
# 에러가 아니지만, 결측값이 존재하므로 나타나는 값 (결측값 혹은 무한대값)
arr = np.array([-1, 2, -3])
print(arr + np.nan)
print(arr + np.inf)

[nan nan nan]
[inf inf inf]


# 인덱싱 & 슬라이싱

In [70]:
arr = np.arange(10)
arr[1:5]

array([1, 2, 3, 4])

In [77]:
# arr = np.arange(10).reshape(2,5)
arr = np.arange(10).reshape(2,5)
arr[0][1]

np.int64(1)

In [82]:
arr = np.arange(10000).reshape(100,100)
# arr[0:4][0:1]

In [86]:
arr = np.arange(4).reshape(2,2)
arr[:2]

array([[0, 1],
       [2, 3]])

In [112]:
arr = np.arange(20).reshape(4, 5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [113]:
# [행슬라이싱, 열슬라이싱] 
# arr[1:4, 2:5] or arr[1:, 2:]

arr[1:4, 2:5]

array([[ 7,  8,  9],
       [12, 13, 14],
       [17, 18, 19]])

In [111]:
arr[1:, 2:]

array([[ 7,  8,  9],
       [12, 13, 14],
       [17, 18, 19]])

In [115]:
# arr[행, 열]
arr[1:, 3:]

array([[ 8,  9],
       [13, 14],
       [18, 19]])

# 브로드캐스팅 연산
- 받은 행렬의 크기가 다른 경우가 많음
- 크기가 다른 배열 간의 연산도 자동으로 맞춰서 처리하는 연산법

In [116]:
a = np.array([1, 2, 3])
b = np.array([1, 2, 3])
a + b

array([2, 4, 6])

In [119]:
a = np.array([1, 2, 3])
b = 3.0  # [3.0, 3.0, 3.0] 형태의 1차원 배열 생성
a + b

array([4., 5., 6.])

In [120]:
A = np.array([[1, 2], [3, 4]])
B = np.array([10, 20])

print(A + B)  # B가 A의 각 행에 더해짐 (브로드캐스팅)

[[11 22]
 [13 24]]


In [173]:
# 연습 문제 1
import numpy as np
a = np.zeros((5,5))
a

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [176]:
np.zeros(25).reshape(5, 5)

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [177]:
# 연습문제 2 출력
a = np.arange(9).reshape(3, 3)
a.shape, a.dtype, a.ndim

((3, 3), dtype('int64'), 2)

In [178]:
# 연습문제 3 슬라이싱
arr = np.arange(16).reshape(4,4)
arr[1:3, 1:3]

array([[ 5,  6],
       [ 9, 10]])

# 조건 연산(numpy 필터링)
- 원하는 결괏값 : True/False

In [186]:
arr = np.array([10, 20, 30])
arr > 18

array([False,  True,  True])

In [182]:
# pandas에서 매우 중요! True 값만 가져옴
arr = np.array([10, 20, 30])
cond = [False, True, True]

arr[cond]

array([20, 30])

In [184]:
arr = np.array([18, 20, 50, 30, 16])
cond = arr > 18 #엑셀의 필터와 동일

arr[cond]

array([20, 50, 30])

In [185]:
arr = np.array([18, 20, 50, 30, 16])
arr[arr > 18]

array([20, 50, 30])

In [191]:
# 다중 조건
arr = np.array([18, 20, 50, 30, 16, 65, 70])
con0 = arr > 18
con1 = arr < 65
arr[con0 & con1] 

array([20, 50, 30])

In [193]:
# | 둘 중 하나라도 참이면 선택됨
arr[con0 | con1]

array([18, 20, 50, 30, 16, 65, 70])

In [195]:
# 권장사항, 이유 : pandas 다중조건 필터링할 때는 아래 방법으로만 가능
# () 반드시 필요함
arr[(con0|con1)]

array([18, 20, 50, 30, 16, 65, 70])

## np.where
- np.where(조건, 참일때 출력, 거짓일 때 출력)

In [196]:
import numpy as np
a = np.arange(10)
a
np.where(a < 5, a, 10*a)

array([ 0,  1,  2,  3,  4, 50, 60, 70, 80, 90])

## 함수와 메서드

In [207]:
arr = np.arange(8).reshape(2, 4) # shape(행갯수, 열갯수)
arr

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [208]:
arr.sum() # arr.sum(axis = None)

np.int64(28)

In [209]:
arr.sum(axis=0) # x축 방향으로 데이터의 합 구하기

array([ 4,  6,  8, 10])

In [210]:
arr.sum(axis = 1) # y축 방향으로 데이터의 합 구하기

array([ 6, 22])

In [226]:
# 무작위 랜덤 함수 만들기
np.random.seed(42) # 머신러닝 할 때, 이 코드를 자주 사용, 42대신 아무 숫자나 써도 됨
np.random.randint(10)

6

In [228]:
np.random.randint(46, size = 6) # 46이 의미하는 것은 0~45번째까지의 숫자 중 무작위로 가져오겠다.

array([18, 22, 10, 10, 23, 35])

In [246]:
np.random.randint(46, size = (3,4))

array([[29, 36, 22, 38],
       [44, 14, 42, 28],
       [35, 12, 31,  6]])

In [247]:
x = np.linspace(0, 100, 11) # 등차수열
print(x)

[  0.  10.  20.  30.  40.  50.  60.  70.  80.  90. 100.]


# Pandas Series

In [248]:
import pandas as pd
pd.__version__

'2.2.3'

In [249]:
data = [10, 20, 30]
s = pd.Series(data)
s

0    10
1    20
2    30
dtype: int64

In [250]:
print(type(s))

<class 'pandas.core.series.Series'>


In [255]:
import numpy as np
data = np.arange(5)
s = pd.Series(data)
s

0    0
1    1
2    2
3    3
4    4
dtype: int64

In [256]:
df = pd.DataFrame(data)
df

0
0  0
1  1
2  2
3  3
4  4

In [257]:
data = ["시가", "고가"]
s = pd.Series(data)
s

0    시가
1    고가
dtype: object

In [260]:
data = [80000, "90000"]
s = pd.Series(data)
s

# object 타입 : 여러 데이터 형식이 섞여있어 형식이 아직 정해지지 않은 상태, 카테고리 형식으로 변형 후 작업하는게 편의

0    80000
1    90000
dtype: object

## 시리즈 인덱스

In [266]:
data = [1000, 2000, 3000]
s = pd.Series(data)
print(s.index, type(s.index))

RangeIndex(start=0, stop=3, step=1) <class 'pandas.core.indexes.range.RangeIndex'>


In [267]:
list(s.index)

[0, 1, 2]

In [268]:
s.index.to_list()

[0, 1, 2]

In [270]:
# help(s.index) #클래스에는 항상 속성과 메서드가 존재함

In [291]:
# 시리즈 생성하면서 인덱스도 같이 생성

data = [1000, 2000, 3000]
index = ['메로나', '비비빅', '월드콘']

s = pd.Series(data = data, index = index)
s

메로나    1000
비비빅    2000
월드콘    3000
dtype: int64

In [292]:
s.index

Index(['메로나', '비비빅', '월드콘'], dtype='object')

In [293]:
s.values # numpy 배열
print(type(s.values))
print(s.values)

<class 'numpy.ndarray'>
[1000 2000 3000]


## 시리즈 인덱싱

In [294]:
print(s.iloc[0])

1000


In [295]:
print(s.iloc[1])

2000


In [296]:
print(s.iloc[2])

3000


In [297]:
print(s.loc["메로나"])

1000


- iloc 는 인덱스 번호, loc는 키값 

In [312]:
data = [1000, 2000, 3000]
index = ['메로나', '비비빅', '월드콘']
s2 = pd.Series(data=data)
print(s2.iloc[0]) # 인덱스가 정의되지 않아도 작동함
# print(s2.loc['메로나']) # 인덱스를 정의해줘야 작동함
s2.index.to_list()

1000


[0, 1, 2]

In [310]:
print(s2.iloc[0]) # iloc에서의 0은 위치 0
print(s2.loc[0]) # loc에서의 0은 라벨 0, 기본값

1000
1000


## 슬라이싱

In [313]:
s

메로나    1000
비비빅    2000
월드콘    3000
dtype: int64

In [314]:
s2

0    1000
1    2000
2    3000
dtype: int64

In [317]:
s.iloc[0:2] # 위치 데이터

메로나    1000
비비빅    2000
dtype: int64

In [318]:
s.loc['메로나':'비비빅'] # 인덱스 데이터

메로나    1000
비비빅    2000
dtype: int64

In [321]:
s2.iloc[0:2] # 2번 위치 전까지

0    1000
1    2000
dtype: int64

In [322]:
s2.loc[0:2] # 인덱스 번호가 2번인 것 까지

0    1000
1    2000
2    3000
dtype: int64

## 시리즈 수정/추가/삭제

In [333]:
data = [1000, 2000, 3000]
index = ['메로나', '비비빅', '월드콘']

s = pd.Series(data = data, index = index)
s

메로나    1000
비비빅    2000
월드콘    3000
dtype: int64

In [334]:
s['메로나'] = 500
s

메로나     500
비비빅    2000
월드콘    3000
dtype: int64

In [329]:
s

메로나    1000
비비빅    2000
월드콘    3000
dtype: int64

In [335]:
s.loc['메로나'] = 500 # 딕셔너리에서 'key' : value 와 비슷, 이 방법을 가장 추천
s

메로나     500
비비빅    2000
월드콘    3000
dtype: int64

In [332]:
s.iloc[0] = 500 # 가능은 하지만 데이터가 많아질 경우 쓰기 어렵고, 비직관적임
s

메로나     500
비비빅    2000
월드콘    3000
dtype: int64

# 시리즈 연산

In [342]:
import pandas as pd 

evan = pd.Series([10, 20, 30], index=['NAVER', 'APPLE', 'NVDIA'])
딸1 = pd.Series([10, 30, 20], index=['NVDIA', 'NAVER', 'APPLE'])

evan

NAVER    10
APPLE    20
NVDIA    30
dtype: int64

In [340]:
딸1

NVDIA    10
NAVER    30
APPLE    20
dtype: int64

In [343]:
# 인덱스 순서와 상관없이 연산이 잘 됨
evan + 딸1

APPLE    40
NAVER    40
NVDIA    40
dtype: int64

In [345]:
evan = pd.Series([10, 20, 30], index=['NAVER', 'APPLE', '테슬라'])
딸1 = pd.Series([10, 30, 20], index=['NVDIA', 'NAVER', 'APPLE'])

evan + 딸1
# NaN(결측값) 처리, pandas는 인덱스를 기준으로 값을 매칭

APPLE    40.0
NAVER    40.0
NVDIA     NaN
테슬라       NaN
dtype: float64

In [359]:
date = ["6/1", "6/2", "6/3", "6/4", "6/5"]
high = pd.Series([42800, 42700, 42050, 42950, 43000], index=date) # 매도
low = pd.Series([42150, 42150, 41300, 42150, 42350] , index=date) # 매수

diff = high - low
print(diff)

6/1    650
6/2    550
6/3    750
6/4    800
6/5    650
dtype: int64


In [358]:
# pandas에서는 반복문 없이 diff.idxmax()로 해결 가능
diff.idxmax(), diff[diff.idxmax()]

('6/4', np.int64(800))

In [356]:
diff.idxmin(), diff[diff.idxmin()]

('6/2', np.int64(550))

In [361]:
profit = high / low # 단순 수익률
profit

6/1    1.015421
6/2    1.013049
6/3    1.018160
6/4    1.018980
6/5    1.015348
dtype: float64

In [363]:
profit.cumprod() # 누적합 메서드

6/1    1.015421
6/2    1.028671
6/3    1.047351
6/4    1.067230
6/5    1.083610
dtype: float64

# 시리즈와 Map

In [366]:
s = pd.Series(['1,234', '5,689', '12,345'])
s 

0     1,234
1     5,689
2    12,345
dtype: object

In [371]:
# 문자를 정수로 변환
text = '1,234'
result = int(text.replace(',','')) # , 제거 후 정수로
type(result), result

(int, 1234)

In [379]:
# 반복문으로 처리하기
num_str = ['1,234', '5,678', '12,345']
result = []
for num in num_str:
    temp = int(num.replace(',', ''))
    result.append(temp)

result

[1234, 5678, 12345]

In [380]:
# 사용자함수로 처리하기
def rm_comma(x):
    return int(x.replace(',', ''))

In [378]:
s = pd.Series(['1,234', '5,689', '12,345'])
result = s.map(rm_comma)
result

0     1234
1     5689
2    12345
dtype: int64

In [382]:
def remove_dollar_sign(x):
    return float(x.replace('$', '').replace(',', ''))
s = pd.Series(['$1,234.56', '$5,678.90', '$12,345.67'])
result = s.map(remove_dollar_sign)

result

0     1234.56
1     5678.90
2    12345.67
dtype: float64

### 문제
- 기준점 > 13
    + 크다 or 작다

In [388]:
def size_check(x):
    if x > 13:
        return "13보다 크다"
    else: 
        return "13보다 작거나 같다"

In [389]:
s = pd.Series([5, 10, 15, 20])
s

0     5
1    10
2    15
3    20
dtype: int64

In [390]:
s.map(size_check)

0    13보다 작거나 같다
1    13보다 작거나 같다
2        13보다 크다
3        13보다 크다
dtype: object

In [395]:
#lambda, map(=apply) 사용
result = s.map(lambda x: "크다" if x >= 13 else '작다')
print(result)

0    작다
1    작다
2    크다
3    크다
dtype: object


In [394]:
result = s.apply(lambda x: "크다" if x >= 13 else '작다')
print(result)

0    작다
1    작다
2    크다
3    크다
dtype: object


# 시리즈 필터링

In [397]:
data = [42500, 42550, 41800, 42550, 42650]
index = ['2019-05-31', '2019-05-30', '2019-05-29', '2019-05-28', '2019-05-27']
s = pd.Series(data=data, index=index)
s

2019-05-31    42500
2019-05-30    42550
2019-05-29    41800
2019-05-28    42550
2019-05-27    42650
dtype: int64

In [398]:
cond = s > 42000
print(cond)

2019-05-31     True
2019-05-30     True
2019-05-29    False
2019-05-28     True
2019-05-27     True
dtype: bool


In [399]:
s[cond]

2019-05-31    42500
2019-05-30    42550
2019-05-28    42550
2019-05-27    42650
dtype: int64

In [400]:
s[s>42000]

2019-05-31    42500
2019-05-30    42550
2019-05-28    42550
2019-05-27    42650
dtype: int64

In [412]:
from pandas import Series
# import pandas as pd
# pd.Series()

close = [42500, 42550, 41800, 42550, 42650]
open = [42600, 42200, 41850, 42550, 42500]
index = ['2019-05-31', '2019-05-30', '2019-05-29', '2019-05-28', '2019-05-27']

open = pd.Series(data=open, index=index)
close = pd.Series(data=close, index=index)

# 문제 : 종가가 시가보다 높은 날을 구하세요.

close[close > open]

2019-05-30    42550
2019-05-27    42650
dtype: int64